# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170404_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
