# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_large',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
