---
- hosts: all
  sudo: yes
  vars:
    vagrant_path: "/home/vagrant"

  tasks:
    - name: Update apt cache
      apt: update_cache=yes
      sudo: yes

    - name: Install general packages
      apt: name={{ item }} state=latest
      sudo: yes
      with_items:
        - htop

    - name: Install python3
      apt: name={{ item }} state=latest
      sudo: yes
      with_items:
        - python3

    - name: Install setuptools
      apt: name={{ item }} state=latest
      sudo: yes
      with_items:
        - python-setuptools

    - name: Install python3 dev packages
      apt: name={{item}} state=latest
      sudo: yes
      with_items:
        - python3-dev
        - libpq-dev
        - libffi-dev
        - libtiff5-dev
        - libjpeg8-dev
        - zlib1g-dev
        - libfreetype6-dev
        - liblcms2-dev
        - libwebp-dev
        - tcl8.6-dev
        - tk8.6-dev
        - python-tk

    - name: Install pip with easy_install
      easy_install: name=pip

    - name: Install virtualenv with pip
      pip: name=virtualenv

    - name: Install virtualenvwrapper with pip
      pip: name=virtualenvwrapper

    - name: Configure virtualenvwrapper and django env vars
      blockinfile:
        dest: /home/vagrant/.bashrc
        block: |
            export WORKON_HOME=/.virtualenvs
            export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
            export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
            source /usr/local/bin/virtualenvwrapper.sh
            export SECRET_KEY='c7el5n*m4*%50%bo7#0i(ethv6qbz*7++2op*1p+h5yj1zjqe7'
            export DJANGO_SETTINGS_MODULE=smg.settings.development
            export LC_ALL="en_US.UTF-8"
            export LC_CTYPE="en_US.UTF-8"

    - name: Make virtualenv
      shell: virtualenv -p /usr/bin/python3 /.virtualenvs/ads
      sudo: yes

    - name: Making vagrant user the owner of /.virtualenvs dir
      shell: chown -R vagrant /.virtualenvs
      sudo: yes

    - name: Add PostgreSQL repository
      apt_repository: repo="deb https://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" state=present

    - name: Fetch PostgreSQL repository key
      shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

    - name: Install PostgreSQL
      apt: name=postgresql state=installed

    - name: Install PostgreSQL Stuff
      apt: name={{item}} state=installed
      with_items:
        - postgresql-contrib
        - python-psycopg2

    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=restarted enabled=yes

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  vars:
    dbname: smg_db
    dbuser: admin
    dbpassword: homm1994

  tasks:
    - name: Create db
      postgresql_db: name={{ dbname }}

    - name: Create user
      postgresql_user: db={{ dbname }} name={{ dbuser }} password={{ dbpassword }} role_attr_flags=SUPERUSER priv=ALL
